### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by 23jdn** [luckyfuture0177/ReZeroBypassAV#1]
delete

**Comment by luckyfuture0177** [comment]
> 这么好的汇总不能不更新啊,秋梨膏
@23jdn

已经提上日程了，这个月就继续做恶意代码方面的研究

**Comment by 23jdn** [comment]
我也打算做个汇总,方便留个email吗 交流.

**Comment by luckyfuture0177** [comment]
@23jdn  luckyfuture0177@163.com
